# Generated by Django 4.2.29 on 2026-04-18 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_face_recording'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_area', models.CharField(help_text='Área profissional selecionada', max_length=255)),
                ('transcript', models.TextField(help_text='Transcrição da entrevista')),
                ('analysis', models.JSONField(help_text='Análise estruturada da entrevista via LLM')),
                ('report', models.TextField(help_text='Relatório final personalizado')),
                ('behavioral_data', models.JSONField(default=dict, help_text='Dados comportamentais da gravação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recording', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.facerecording')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
